In [0]:
# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.0-{platform}-linux_x86_64.whl torchvision

In [0]:
import torch
import numpy as np

In [0]:
# Sigmoid
def activation(x):
  return 1 / (1 + torch.exp(-x))

In [0]:
# Generate some data
torch.manual_seed(7)

# Features, 5 random variables
features = torch.randn((1, 5))

# random weights
weights = torch.randn_like(features)

bias = torch.randn((1, 1))


In [5]:
# output
y_hat = activation(torch.sum(features * weights) + bias)
y_hat


tensor([[ 0.1595]])

In [6]:
# calculate using matrix multiplication
y_hat = activation(torch.mm(features, weights.view(5, 1)) + bias)
y_hat


tensor([[ 0.1595]])

In [0]:
## Multi-layer neural network

In [0]:
# Generate some data
torch.manual_seed(7)

# features are 3 random variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]  # number of input units
n_hidden = 2  # number of hidden units
n_output = 1  # number of output units

# Weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)

# Weights for hidden to output layer
w2 = torch.randn(n_hidden, n_output)

# bias terms for hidden to output
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

In [9]:
# Calculate the output for multi-layer neural network

h = activation(torch.mm(features, w1) + b1)

y_hat = activation(torch.mm(h, w2) + b2)
y_hat

tensor([[ 0.3171]])

In [0]:
## Numpy to Torch and back 

In [11]:
a = np.random.rand(4, 3)
a

array([[0.02132064, 0.8194808 , 0.1970562 ],
       [0.89043176, 0.78969421, 0.3905835 ],
       [0.19445186, 0.6277504 , 0.8746853 ],
       [0.46627941, 0.00410953, 0.42500229]])

In [12]:
b = torch.from_numpy(a)
b

tensor([[ 0.0213,  0.8195,  0.1971],
        [ 0.8904,  0.7897,  0.3906],
        [ 0.1945,  0.6278,  0.8747],
        [ 0.4663,  0.0041,  0.4250]], dtype=torch.float64)

In [13]:
b.numpy()

array([[0.02132064, 0.8194808 , 0.1970562 ],
       [0.89043176, 0.78969421, 0.3905835 ],
       [0.19445186, 0.6277504 , 0.8746853 ],
       [0.46627941, 0.00410953, 0.42500229]])

In [14]:
b.mul_(2)

tensor([[ 0.0426,  1.6390,  0.3941],
        [ 1.7809,  1.5794,  0.7812],
        [ 0.3889,  1.2555,  1.7494],
        [ 0.9326,  0.0082,  0.8500]], dtype=torch.float64)

In [15]:
a

array([[0.04264129, 1.63896161, 0.39411241],
       [1.78086353, 1.57938843, 0.781167  ],
       [0.38890372, 1.2555008 , 1.74937061],
       [0.93255883, 0.00821907, 0.85000457]])